In [1]:
import numpy as np
import pandas as pd

In [5]:
## Write a function so that the columns of the output matrix are powers of the input  vector.
## Method-1
x=np.array([1,2,3,4,5])
n=5
np.vander(x,n)
    
   

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

In [7]:
### method-2
power=[x**(n-1-i) for i in range(n)]
power

[array([  1,  16,  81, 256, 625], dtype=int32),
 array([  1,   8,  27,  64, 125], dtype=int32),
 array([ 1,  4,  9, 16, 25], dtype=int32),
 array([1, 2, 3, 4, 5], dtype=int32),
 array([1, 1, 1, 1, 1], dtype=int32)]

In [8]:
matrix=np.column_stack(power)
print(matrix)


[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [9]:
## Write a function to find moving average in an array over a window:
## Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.
def moving_average(a, n=3) :
    asum = np.cumsum(a, dtype=float)
    asum[n:] = asum[n:] - asum[:-n] 
    return asum[n - 1:] / n

In [10]:
a=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]

In [11]:
a1=np.array(a)

In [12]:
a1

array([  3,   5,   7,   2,   8,  10,  11,  65,  72,  81,  99, 100, 150])

In [13]:
np.array(moving_average(a1,n=3)).round(2)

array([  5.  ,   4.67,   5.67,   6.67,   9.67,  28.67,  49.33,  72.67,
        84.  ,  93.33, 116.33])